# Generated by Django 5.2.3 on 2025-12-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_max', models.IntegerField(default=0)),
                ('storage_now', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('action_order', models.CharField(verbose_name='Ordre donné')),
                ('action_now', models.CharField(verbose_name='Action en cours')),
                ('home_station', models.CharField(verbose_name='Home')),
                ('system_target', models.CharField(verbose_name='Cible')),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Nom')),
                ('storage', models.IntegerField(default=0)),
                ('system_location', models.CharField(verbose_name='Cible')),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
            ],
        ),
    ]
