# Generated by Django 5.2.3 on 2025-12-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Nom')),
                ('width', models.IntegerField(verbose_name='Largeur du system')),
                ('height', models.IntegerField(verbose_name='Hauteur du system')),
            ],
        ),
        migrations.CreateModel(
            name='Ore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Nom')),
                ('storage', models.IntegerField(default=0)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
            ],
        )
    ]
