# Generated by Django 5.2.3 on 2025-12-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle', '0002_system_ore_station_system_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ore',
            name='system_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idle.system'),
        ),
        migrations.AddField(
            model_name='station',
            name='system_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idle.system'),
        ),
    ]
