# Generated by Django 5.2.3 on 2025-12-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle', '0003_ore_system_id_station_system_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='minning_speed',
            field=models.IntegerField(default=0),
        ),
    ]
