# Generated by Django 5.2.3 on 2025-12-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle', '0004_ship_minning_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='action_now',
            field=models.CharField(default='', verbose_name='Action en cours'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='action_order',
            field=models.CharField(default='', verbose_name='Ordre donné'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='home_station',
            field=models.CharField(default='', verbose_name='Home'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='system_target',
            field=models.CharField(default='', verbose_name='Cible'),
        ),
    ]
