# Generated by Django 5.2.3 on 2025-12-28 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('idle', '0005_alter_ship_action_now_alter_ship_action_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='station_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idle.station'),
        ),
        migrations.AddField(
            model_name='ship',
            name='system_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idle.system'),
        ),
        migrations.AddField(
            model_name='ship',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_by_ships', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ship',
            name='target_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReportSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Nom')),
                ('system_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idle.system')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSystemTic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Numero de tic pour le meme ship / rapport')),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('action_now', models.CharField()),
                ('report_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idle.reportsystem')),
                ('ship_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idle.ship')),
            ],
        ),
    ]
