# Generated by Django 5.2.3 on 2025-12-28 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle', '0006_ship_station_fk_ship_system_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsystemtic',
            name='action_now',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='reportsystemtic',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Numero de tic pour le meme ship / rapport'),
        ),
        migrations.AlterField(
            model_name='reportsystemtic',
            name='pos_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportsystemtic',
            name='pos_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportsystemtic',
            name='report_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idle.reportsystem'),
        ),
        migrations.AlterField(
            model_name='reportsystemtic',
            name='ship_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idle.ship'),
        ),
    ]
