# Generated by Django 5.2.3 on 2025-12-28 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle', '0007_alter_reportsystemtic_action_now_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsystem',
            name='cached_dict',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='reportsystem',
            name='name',
            field=models.CharField(null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='reportsystem',
            name='system_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idle.system'),
        ),
    ]
