# Generated by Django 5.2.3 on 2025-12-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle', '0008_reportsystem_cached_dict_alter_reportsystem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsystemtic',
            name='storage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reportsystemtic',
            name='target_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reportsystemtic',
            name='target_model',
            field=models.CharField(null=True),
        ),
    ]
