# Generated by Django 5.2.3 on 2026-01-10 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle', '0009_reportsystemtic_storage_reportsystemtic_target_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsystem',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 10, 11, 45, 11, 305718)),
        ),
        migrations.AddField(
            model_name='reportsystem',
            name='time_stop',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 10, 11, 45, 11, 305739)),
        ),
        migrations.AddField(
            model_name='system',
            name='report_time_duration',
            field=models.IntegerField(default=10, verbose_name='Durée de chaque report en secondes'),
        ),
    ]
