# Generated by Django 5.2.3 on 2026-01-10 20:08

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle', '0010_reportsystem_time_start_reportsystem_time_stop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsystemtic',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reportsystem',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 10, 20, 8, 29, 798789, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reportsystem',
            name='time_stop',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 10, 20, 8, 29, 798814, tzinfo=datetime.timezone.utc)),
        ),
    ]
