# Generated by Django 5.2.3 on 2026-01-16 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle', '0011_reportsystemtic_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsystem',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 19, 18, 40, 950821, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reportsystem',
            name='time_stop',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 19, 18, 40, 950874, tzinfo=datetime.timezone.utc)),
        ),
    ]
