# Generated by Django 5.2.3 on 2026-01-17 10:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle', '0012_alter_reportsystem_time_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='is_dock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportsystem',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 17, 10, 25, 20, 268452, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reportsystem',
            name='time_stop',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 17, 10, 25, 20, 268486, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ship',
            name='action_order',
            field=models.CharField(default='', verbose_name='Ordre donné par le joueur'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='station_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='idle.station', verbose_name='Home station of player'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='system_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='idle.system'),
        ),
    ]
