# Generated by Django 5.2.3 on 2026-01-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle', '0013_ship_is_dock_alter_reportsystem_time_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsystem',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reportsystem',
            name='time_stop',
            field=models.DateTimeField(null=True),
        ),
    ]
