# Generated by Django 5.2.3 on 2026-01-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle', '0014_alter_reportsystem_time_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsystemtic',
            name='is_dock',
            field=models.BooleanField(default=False),
        ),
    ]
